Fix missing space in non-existing-library message
Before this change the exception was printed as:

Exception: Library 'papers' does not seem to exist

To add a library simply write the followingin your configuration ...