Add python3.10 to versions to run tests on (#343)
* Add python 3.10 to versions to run tests on

Need to quote 3.10, or else it CI tries (and fails) to install
python3.1.

* commands/merge: silence coverage error about too many empty lines

* commands/browse: fix coverage error from whitespace around =

* Fix missing space in non-existing-library message

Before this change the exception was printed as:

Exception: Library 'papers' does not seem to exist

To add a library simply write the followingin your configuration ...